---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: captcha
  namespace: xero
  labels:
    app: captcha
spec:
  replicas: 5
  selector:
    matchLabels:
      app: captcha
  template:
    metadata:
      labels:
        app: captcha
    spec:
      containers:
      - name: captcha
        image: hu13er/captcha:latest
        env:
          - name: "CAPTCHA_ADDR"
            value: "0.0.0.0:8000"
          - name: "CAPTCHA_DIR"
            value: "/captcha/"
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: captcha
  namespace: xero
spec:
  selector:
    app: captcha
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: captcha
  namespace: xero
  annotations:
    kubernetes.io/tls-acme: "true" 
spec:
  ingressClassName: nginx
  rules:
  tls:
    - hosts:
      - halftimepad.roboepics.com
      secretName: halftimepad-tls
  - host: "captcha.roboepics.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: captcha
            port:
              number: 80

